# Generated by Django 3.2.7 on 2021-11-01 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0003_auto_20211101_1217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Biodata',
        ),
    ]
